import Head from 'next/head'
import { useEffect } from 'react';
import UserService from '../core/services/UserService';
import styles from '../ui/styles/Home.module.css'

export default function Home() {
  async function find() {
    const response = await new UserService().find("felipesantosds")

    console.log(response);
  }

  useEffect(() => {
    find();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello, World!</h1>
      </main>
    </div>
  )
}
